[project]
name = "hierarchical_segmentation_selector"
version = "0.1.0"
authors = [
    {name = "Baptiste Esteban", email = "baptiste.esteban@epita.fr"}
]
requires-python = ">=3.13"
dependencies = [
    "dash>=4.4.1",
    "dash-bootstrap-components>=2.0.4",
    "imageio>=2.37.4",
    "loguru>=0.7.3",
    "numba>=0.67.0",
    "scikit-image>=0.26.0",
]

[project.optional-dependencies]
doc = [
    "mkdocs>=1.6.1",
    "mkdocs-mermaid2-plugin>=1.2.3",
    "mkdocs-material>=9.7.7",
]

[dependency-groups]
dev = [
    "ruff>=0.16.8",
]
